### PR TITLE
This makes more sense

### PR DESCRIPTION
**Pull request by Skull3x**

### CODE REVIEW

**Comment by AndreTheGamer** [comment]
Have you even tested it -.- 

:hushed:

**Comment by SkygridRex** [comment]
Looks good but only owner can merge this

**Comment by TheKillerTacos** [comment]
there is no sense by merging this, plugin reboot will start withing 2 weeks, i will delete this plugin and remake it at PocketProjects.

**Comment by SkygridRex** [comment]
It's not in december?

**Comment by TheKillerTacos** [comment]
i placed the date wrong, correct it plz, im busy on here :L,

**Comment by SkygridRex** [comment]
En Colombia el formato de la fecha es dd/mm/aaaa

**Comment by SkygridRex** [comment]
I can not change the name im not owner

**Comment by TheKillerTacos** [comment]
ill do it later

**Comment by SkygridRex** [comment]
So, when you will close all issues que merge request?

**Comment by TheKillerTacos** [comment]
yep, i will Close this Organization, name will be kept, and reopen this project on PocketProjects

**Comment by SkygridRex** [comment]
Conservarás el nombre con que fin?

**Comment by TheKillerTacos** [comment]
Para Creaciones, decir, como 'Compañia', la usare como para projectos Cerrados, Video Juegos, Aplicaciones y otros,

**Comment by SkygridRex** [comment]
Borralo ahora pasalo de una vez para ponernos manos a la obra

**Comment by AndreTheGamer** [comment]
?

**Comment by SkygridRex** [comment]
What happen?

**Comment by AndreTheGamer** [comment]
i don't understand what you guys are saying :P

**Comment by TheKillerTacos** [comment]
we may port Skyblock to PocketProjects, but first ** I'LL ** Make the base plugin, but first we work at Pocketpanel

**Comment by AndreTheGamer** [comment]
ok and SkyBlock plugin seems basic and should take 1 week or even days to finishe.. XD

**Comment by TheKillerTacos** [comment]
Skyblock base its simple, but **ALL** the features will take some months, i may have island management for PocketPanel, like see list of player in that island, is island claimed, etc

**Comment by SkygridRex** [comment]
@TheKillerTacos vamos mueve esta repo

**Comment by TheKillerTacos** [comment]
DELETIN THIS CRUP

**Pull request closed without merging**
